#!/bin/sh

## tested with upgrading Debian Wheezy OpenVZ containers #########
## for a systemd free Debian Jessie desktop see Antix Linux 15  ##
## http://antix.mepis.org/index.php?title=Main_Page  #############
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
export DEBCONF_NOWARNINGS=yes
# update wheezy
apt-get -y update
apt-get -y upgrade
# edit sources wheexy ---> devuan jessie
wget http://packages.devuan.org/devuan/pool/main/d/devuan-baseconf/devuan-baseconf_0.6.4%2bdevuan1_all.deb
dpkg -i devuan*.deb
rm -f devuan*.deb
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 94532124541922FB
# wheezy ---> jessie upgrade
apt-get -y remove plymouth
apt-get update
apt-get -y --download-only dist-upgrade
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y install inetutils-syslogd htop upstart sysvinit-utils
apt-get -y autoremove
apt-get clean

