#!/bin/sh

## tested with upgrading Debian Wheezy OpenVZ containers #########
## for a systemd free Debian Jessie desktop see Antix Linux 15  ##
## http://antix.mepis.org/index.php?title=Main_Page  #############
export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY=critical
export DEBCONF_NOWARNINGS=yes
# update wheezy
apt-get -y update
apt-get -y upgrade
# edit sources wheexy ---> jessie
echo 'deb http://ftp.debian.org/debian jessie main contrib non-free' > /etc/apt/sources.list
echo 'deb http://security.debian.org jessie/updates main contrib non-free' >> /etc/apt/sources.list
# prevent systemd from installing
echo 'Package: *systemd*\nPin: origin ""\nPin-Priority: -1' > /etc/apt/preferences.d/systemd
echo '\nPackage: systemd:amd64\nPin: origin ""\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
echo '\nPackage: systemd:i386\nPin: origin ""\nPin-Priority: -1' >> /etc/apt/preferences.d/systemd
# wheezy ---> jessie upgrade
apt-get -y remove plymouth
apt-get update
apt-get -y --download-only dist-upgrade
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y install upstart sysvinit-utils
apt-get -y remove --purge --auto-remove systemd
apt-get clean

