#!/bin/sh

## backporting debhelper to Debian Jessie (to build libassuan 2.4.2+) ##

pkgname=debhelper
pkgver=9.20151225
format=tar.xz
deb_src=
sources=http://http.debian.net/debian/pool/main/d/$pkgname/${pkgname}_$pkgver.$format
build_dir=$PWD/$pkgname-$pkgver

extract () {
  if [ -f $1 ] ; then
      case $1 in
          *.tar.bz2)   tar xvjf $1    ;;
          *.tar.gz)    tar xvzf $1    ;;
          *.tar.xz)    tar xvfJ $1    ;;
          *)           echo "don't know how to extract '$1'..." ;;
      esac
  else
      echo "'$1' is not a valid file!"
  fi
}

# start
rm -rf $build_dir

for file in $sources $deb_src; do
  if [ ! -f "$(basename $file)" ]; then
    wget $file
  fi
done

extract ${pkgname}_$pkgver.$format
mv $pkgname $pkgname-$pkgver
cd $build_dir
sudo mk-build-deps --install debian/control
dh_make --createorig
dpkg-buildpackage
# install build depends for libassuan
sudo dpkg -i ../*.deb


