#!/bin/sh

## backporting libassuan to Debian Jessie ##

pkgname=libassuan
pkgver=2.4.2
format=tar.bz2
deb_src=http://http.debian.net/debian/pool/main/liba/libassuan/libassuan_$pkgver-2.debian.tar.xz
sources="ftp://ftp.gnupg.org/gcrypt/$pkgname/$pkgname-$pkgver.$format
  ftp://ftp.gnupg.org/gcrypt/$pkgname/$pkgname-$pkgver.$format.sig
  "

extract () {
  if [ -f $1 ] ; then
      case $1 in
          *.tar.bz2)   tar xvjf $1    ;;
          *.tar.gz)    tar xvzf $1    ;;
          *.tar.xz)    tar xvfJ $1    ;;
          *)           echo "don't know how to extract '$1'..." ;;
      esac
  else
      echo "'$1' is not a valid file!"
  fi
}

# start
rm -rf $pkgname-$pkgver

for file in $sources $deb_src; do
  if [ ! -f "$(basename $file)" ]; then
    wget $file
  fi
done

extract $(basename $deb_src)
# should show RSA key ID 4F25E3B6 - see: https://www.gnupg.org/signature_key.html
gpg --verify $pkgname-$pkgver.$format.sig $pkgname-$pkgver.$format
extract $pkgname-$pkgver.$format
mv debian ./$pkgname-$pkgver
cd $pkgname-$pkgver
sudo mk-build-deps --install debian/control
dh_make --createorig
dpkg-buildpackage
# add gnupg2 build depends
sudo dpkg -i ../libassuan0_$pkgver*.deb ../libassuan-dev*.deb

